name: Build Unsigned Binaries

on:
  push:
  release:
    types: [released]
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm install --include=dev

      - name: Download uv
        run: npm run download linux

      - name: Build GUI
        run: npm run app:dist

      - name: Publish artifact - GUI
        uses: actions/upload-artifact@v4
        with:
          name: 'Invoke Community Edition.AppImage'
          path: 'dist/Invoke Community Edition.AppImage'

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm install --include=dev

      - name: Download uv
        run: npm run download mac

      - name: Build GUI
        run: npm run app:dist

      - name: Publish artifact - GUI
        uses: actions/upload-artifact@v4
        with:
          name: 'Invoke Community Edition.dmg'
          path: 'dist/Invoke Community Edition.dmg'

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm install --include=dev

      - name: Download uv
        run: npm run download win

      - name: Build GUI
        run: npm run app:dist

      - name: Publish artifact - GUI - UNSIGNED
        uses: actions/upload-artifact@v4
        with:
          name: 'Invoke Community Edition.exe - UNSIGNED'
          path: 'dist/Invoke Community Edition.exe'
